package database;

import core.ConfigManager;
import core.Encryption;
import core.MasterPassword;
import gui.LoginEntry;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.crypto.SecretKey;

public class FirebirdDriver implements IDatabaseDriver {

    private Connection connection;
    
    @Override
    public void connect(ConfigManager.DbConfig config) throws SQLException {
        System.out.println("Connecting to Firebird database...");
        try {
            Class.forName("org.firebirdsql.jdbc.FBDriver");
        } catch (ClassNotFoundException e) {
            System.err.println("Firebird JDBC Driver (Jaybird) not found. Add it to pom.xml.");
            throw new SQLException("Firebird Driver not found", e);
        }

        String host, port, dbName, user, pass;
        try {
            host = Encryption.decryptWithIV(config.host(), MasterPassword.getKey());
            port = Encryption.decryptWithIV(config.port(), MasterPassword.getKey());
            dbName = Encryption.decryptWithIV(config.dbName(), MasterPassword.getKey());
            user = Encryption.decryptWithIV(config.user(), MasterPassword.getKey());
            pass = Encryption.decryptWithIV(config.pass(), MasterPassword.getKey());
        } catch (Exception e) {
            throw new SQLException("Failed to decrypt Firebird credentials", e);
        }

        // Standard Firebird JDBC URL format
        String dbUrl = "jdbc:firebirdsql://" + host + ":" + port + "/" + dbName;
        
        System.out.println("Connecting to Firebird at " + dbUrl);
        connection = DriverManager.getConnection(dbUrl, user, pass);
        System.out.println("Connected to Firebird.");
        
        checkAndCreateloginsTable();
    }
    
    @Override
    public void checkAndCreateloginsTable() throws SQLException {
        if (!doesTableExist("LOGINS") || !isPasswordTableSchemaCorrect("LOGINS")) {
            createloginsTable();
        }
    }
    
    private boolean doesTableExist(String tableName) throws SQLException {
        DatabaseMetaData meta = connection.getMetaData();
        // Firebird often uses uppercase for table names
        try (ResultSet rs = meta.getTables(null, null, tableName.toUpperCase(), new String[] { "TABLE" })) {
            return rs.next();
        }
    }

    private boolean isPasswordTableSchemaCorrect(String tableName) throws SQLException {
        String[] requiredColumns = { "ID", "NAME", "USERNAME", "PASSWORD", "URL", "NOTES" };
        DatabaseMetaData meta = connection.getMetaData();
        try (ResultSet columns = meta.getColumns(null, null, tableName.toUpperCase(), null)) {
            int foundColumns = 0;
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");
                for (String required : requiredColumns) {
                    if (required.equalsIgnoreCase(columnName)) {
                        foundColumns++;
                        break;
                    }
                }
            }
            return foundColumns == requiredColumns.length;
        }
    }

    private void createloginsTable() throws SQLException {
        // Firebird SQL for auto-incrementing ID and text fields
        String createTableSQL = "CREATE TABLE LOGINS (" +
            "ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "NAME BLOB SUB_TYPE TEXT NOT NULL, " +
            "USERNAME BLOB SUB_TYPE TEXT NOT NULL, " +
            "PASSWORD BLOB SUB_TYPE TEXT NOT NULL, " +
            "URL BLOB SUB_TYPE TEXT, " +
            "NOTES BLOB SUB_TYPE TEXT);";
        
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(createTableSQL);
            System.out.println("Firebird logins table created or verified.");
        } catch (SQLException e) {
            // Ignore "Table 'LOGINS' already exists" error
            if (!e.getMessage().contains("Table 'LOGINS' already exists")) {
                throw e;
            }
        }
    }

    @Override
    public String createLogin(String name, String username, String password, String url, String notes) {
        String sql = "INSERT INTO LOGINS (NAME, USERNAME, PASSWORD, URL, NOTES) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            pstmt.setString(1, Encryption.encryptWithIV(name, MasterPassword.getKey()));
            pstmt.setString(2, Encryption.encryptWithIV(username, MasterPassword.getKey()));
            pstmt.setString(3, Encryption.encryptWithIV(password, MasterPassword.getKey()));
            pstmt.setString(4, Encryption.encryptWithIV(url, MasterPassword.getKey()));
            pstmt.setString(5, Encryption.encryptWithIV(notes, MasterPassword.getKey()));
            
            int affectedRows = pstmt.executeUpdate();

            if (affectedRows > 0) {
                try (ResultSet rs = pstmt.getGeneratedKeys()) {
                    if (rs.next()) {
                        return String.valueOf(rs.getLong(1)); // REFACTORED
                    }
                }
            }
            return null;
        } catch (SQLException e) {
            System.err.println("Create login failed: " + e.getMessage());
            return null;
        } catch (Exception e) {
            System.err.println("Encryption failed during create: " + e.getMessage());
            return null;
        }
    }

    @Override
    public boolean deleteLogin(String id) { // REFACTORED
        String sql = "DELETE FROM LOGINS WHERE ID = ?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setLong(1, Long.parseLong(id)); // REFACTORED
            int affectedRows = pstmt.executeUpdate();
            return affectedRows > 0;
        } catch (SQLException | NumberFormatException e) {
            System.err.println("Delete login failed: " + e.getMessage());
            return false;
        }
    }

    @Override
    public List<LoginEntry> getAllLoginEntries(SecretKey masterKey) throws Exception {
        List<LoginEntry> entries = new ArrayList<>();
        String sql = "SELECT ID, NAME, USERNAME, PASSWORD, URL, NOTES FROM LOGINS";
        
        try (PreparedStatement pstmt = connection.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {
            
            while (rs != null && rs.next()) {
                String id = String.valueOf(rs.getLong("ID")); // REFACTORED
                String plainTextName = "!!DECRYPT_ERROR!!";
                String plainTextUser = "!!DECRYPT_ERROR!!";
                String plainTextPass = "!!DECRYPT_ERROR!!";
                String plainTextUrl = "!!DECRYPT_ERROR!!";
                String plainTextNotes = "!!DECRYPT_ERROR!!";
                
                try {
                    plainTextName = Encryption.decryptWithIV(rs.getString("NAME"), masterKey);
                    plainTextUser = Encryption.decryptWithIV(rs.getString("USERNAME"), masterKey);
                    plainTextPass = Encryption.decryptWithIV(rs.getString("PASSWORD"), masterKey);
                    plainTextUrl = Encryption.decryptWithIV(rs.getString("URL"), masterKey);
                    plainTextNotes = Encryption.decryptWithIV(rs.getString("NOTES"), masterKey);
                    
                } catch (Exception e) {
                    System.err.println("Failed to decrypt entry with id " + id + " during migration: " + e.getMessage());
                }
                
                entries.add(new LoginEntry(id, plainTextName, plainTextUser, plainTextPass, plainTextUrl, plainTextNotes));
            }
        }
        return entries;
    }

    @Override
    public void deleteAllLogins() throws SQLException {
        // Firebird's equivalent of truncate is just DELETE
        String sql = "DELETE FROM LOGINS";
        
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(sql);
            System.out.println("Destination table wiped.");
        }
    }

    @Override
    public void closeConnection() {
         try {
            if (connection != null && !connection.isClosed()) {
                System.out.println("Closing Firebird connection...");
                connection.close();
                System.out.println("Firebird connection closed.");
            }
        } catch (SQLException e) {
            System.err.println("Failed to close Firebird connection: " + e.getMessage());
        }
    }
}	